#!/usr/bin/env bash

###
# A CMD or ENTRYPOINT script for a Dockerfile to use to start a Nginx/PHP-FPM
#
##

if [ ! "production" == "$APP_ENV" ] && [ ! "prod" == "$APP_ENV" ]; then
    # Enable xdebug

    ## FPM
    ln -sf /etc/php/7.3/mods-available/xdebug.ini /etc/php/7.3/fpm/conf.d/20-xdebug.ini

    ## CLI
    ln -sf /etc/php/7.3/mods-available/xdebug.ini /etc/php/7.3/cli/conf.d/20-xdebug.ini
else
    # Disable xdebug

    ## FPM
    if [ -e /etc/php/7.3/fpm/conf.d/20-xdebug.ini ]; then
        rm -f /etc/php/7.3/fpm/conf.d/20-xdebug.ini
    fi

    ## CLI
    if [ -e /etc/php/7.3/cli/conf.d/20-xdebug.ini ]; then
        rm -f /etc/php/7.3/cli/conf.d/20-xdebug.ini
    fi
fi

# Config /etc/php/7.3/mods-available/xdebug.ini
# to correctly set the remote_host to your host computer's IP address
sed -i "s/xdebug\.remote_host\=.*/xdebug\.remote_host\=$XDEBUG_HOST/g" /etc/php/7.3/mods-available/xdebug.ini

# start supervisord, which
# in turn will start Nginx/PHP-FPM
/usr/bin/supervisord
