version: '2'
services:
  app:
    extends:
      file: docker-compose.base.yml
      service: app
    ports:
     - "${APP_PORT}:80"
     - "${APP_SECURE_PORT}:443"
  express:
    extends:
      file: docker-compose.base.yml
      service: express
  nuxt:
    extends:
      file: docker-compose.base.yml
      service: nuxt
networks:
  sdnet:
    driver: "bridge"
