version: '2'
services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    image: ball-scrape/app
    restart: always
    environment:
      APP_ENV: "${APP_ENV}"
      XDEBUG_HOST: "${XDEBUG_HOST}"
    volumes:
     - ./express:/var/www/html/backend:cached
     - ./nuxt:/var/www/html/nuxt:cached
    networks:
     - sdnet
  express:
    build:
      context: ./docker/express
      dockerfile: Dockerfile
    image: ball-scrape/node
    restart: always
    volumes:
     - ./express:/var/www/html/express:cached
    networks:
     - sdnet
  frontend:
    build:
      context: ./docker/nuxt
      dockerfile: Dockerfile
    image: ball-scrape/node
    restart: always
    volumes:
     - ./nuxt:/var/www/html/nuxt:cached
    networks:
     - sdnet
