version: '2'
services:
  express:
    extends:
      file: docker-compose.base.yml
      service: express
    ports:
     - "3000:3000"
  nuxt:
    extends:
      file: docker-compose.base.yml
      service: nuxt
    ports:
     - "${APP_PORT}:80"
     - "${APP_SECURE_PORT}:443"
networks:
  sdnet:
    driver: "bridge"
